# Generated by Django 2.0.2 on 2018-06-24 09:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
